/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { EmotionRecognitionService } from "../emotionRecognition.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EmotionRecognitionCreateInput } from "./EmotionRecognitionCreateInput";
import { EmotionRecognition } from "./EmotionRecognition";
import { EmotionRecognitionFindManyArgs } from "./EmotionRecognitionFindManyArgs";
import { EmotionRecognitionWhereUniqueInput } from "./EmotionRecognitionWhereUniqueInput";
import { EmotionRecognitionUpdateInput } from "./EmotionRecognitionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class EmotionRecognitionControllerBase {
  constructor(
    protected readonly service: EmotionRecognitionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: EmotionRecognition })
  @nestAccessControl.UseRoles({
    resource: "EmotionRecognition",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createEmotionRecognition(
    @common.Body() data: EmotionRecognitionCreateInput
  ): Promise<EmotionRecognition> {
    return await this.service.createEmotionRecognition({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        emotion: true,
        id: true,
        timestamp: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [EmotionRecognition] })
  @ApiNestedQuery(EmotionRecognitionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "EmotionRecognition",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async emotionRecognitions(
    @common.Req() request: Request
  ): Promise<EmotionRecognition[]> {
    const args = plainToClass(EmotionRecognitionFindManyArgs, request.query);
    return this.service.emotionRecognitions({
      ...args,
      select: {
        createdAt: true,
        emotion: true,
        id: true,
        timestamp: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: EmotionRecognition })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EmotionRecognition",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async emotionRecognition(
    @common.Param() params: EmotionRecognitionWhereUniqueInput
  ): Promise<EmotionRecognition | null> {
    const result = await this.service.emotionRecognition({
      where: params,
      select: {
        createdAt: true,
        emotion: true,
        id: true,
        timestamp: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: EmotionRecognition })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EmotionRecognition",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateEmotionRecognition(
    @common.Param() params: EmotionRecognitionWhereUniqueInput,
    @common.Body() data: EmotionRecognitionUpdateInput
  ): Promise<EmotionRecognition | null> {
    try {
      return await this.service.updateEmotionRecognition({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          emotion: true,
          id: true,
          timestamp: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: EmotionRecognition })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EmotionRecognition",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteEmotionRecognition(
    @common.Param() params: EmotionRecognitionWhereUniqueInput
  ): Promise<EmotionRecognition | null> {
    try {
      return await this.service.deleteEmotionRecognition({
        where: params,
        select: {
          createdAt: true,
          emotion: true,
          id: true,
          timestamp: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
