/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { EmergencyContactService } from "../emergencyContact.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EmergencyContactCreateInput } from "./EmergencyContactCreateInput";
import { EmergencyContact } from "./EmergencyContact";
import { EmergencyContactFindManyArgs } from "./EmergencyContactFindManyArgs";
import { EmergencyContactWhereUniqueInput } from "./EmergencyContactWhereUniqueInput";
import { EmergencyContactUpdateInput } from "./EmergencyContactUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class EmergencyContactControllerBase {
  constructor(
    protected readonly service: EmergencyContactService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: EmergencyContact })
  @nestAccessControl.UseRoles({
    resource: "EmergencyContact",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createEmergencyContact(
    @common.Body() data: EmergencyContactCreateInput
  ): Promise<EmergencyContact> {
    return await this.service.createEmergencyContact({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        name: true,
        phoneNumber: true,
        relation: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [EmergencyContact] })
  @ApiNestedQuery(EmergencyContactFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "EmergencyContact",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async emergencyContacts(
    @common.Req() request: Request
  ): Promise<EmergencyContact[]> {
    const args = plainToClass(EmergencyContactFindManyArgs, request.query);
    return this.service.emergencyContacts({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        phoneNumber: true,
        relation: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: EmergencyContact })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EmergencyContact",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async emergencyContact(
    @common.Param() params: EmergencyContactWhereUniqueInput
  ): Promise<EmergencyContact | null> {
    const result = await this.service.emergencyContact({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        phoneNumber: true,
        relation: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: EmergencyContact })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EmergencyContact",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateEmergencyContact(
    @common.Param() params: EmergencyContactWhereUniqueInput,
    @common.Body() data: EmergencyContactUpdateInput
  ): Promise<EmergencyContact | null> {
    try {
      return await this.service.updateEmergencyContact({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          name: true,
          phoneNumber: true,
          relation: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: EmergencyContact })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EmergencyContact",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteEmergencyContact(
    @common.Param() params: EmergencyContactWhereUniqueInput
  ): Promise<EmergencyContact | null> {
    try {
      return await this.service.deleteEmergencyContact({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          phoneNumber: true,
          relation: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
