/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AlertCreateNestedManyWithoutUsersInput } from "./AlertCreateNestedManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { EmergencyContactCreateNestedManyWithoutUsersInput } from "./EmergencyContactCreateNestedManyWithoutUsersInput";
import { EmotionRecognitionCreateNestedManyWithoutUsersInput } from "./EmotionRecognitionCreateNestedManyWithoutUsersInput";
import { LocationCreateNestedManyWithoutUsersInput } from "./LocationCreateNestedManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { VoiceCommandCreateNestedManyWithoutUsersInput } from "./VoiceCommandCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => AlertCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AlertCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AlertCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  alerts?: AlertCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => EmergencyContactCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => EmergencyContactCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => EmergencyContactCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  emergencyContacts?: EmergencyContactCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => EmotionRecognitionCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => EmotionRecognitionCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => EmotionRecognitionCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  emotionRecognitions?: EmotionRecognitionCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => LocationCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => LocationCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => LocationCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  locations?: LocationCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: () => VoiceCommandCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => VoiceCommandCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => VoiceCommandCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  voiceCommands?: VoiceCommandCreateNestedManyWithoutUsersInput;
}

export { UserCreateInput as UserCreateInput };
