/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AlertUpdateManyWithoutUsersInput } from "./AlertUpdateManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { EmergencyContactUpdateManyWithoutUsersInput } from "./EmergencyContactUpdateManyWithoutUsersInput";
import { EmotionRecognitionUpdateManyWithoutUsersInput } from "./EmotionRecognitionUpdateManyWithoutUsersInput";
import { LocationUpdateManyWithoutUsersInput } from "./LocationUpdateManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { VoiceCommandUpdateManyWithoutUsersInput } from "./VoiceCommandUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AlertUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AlertUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AlertUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  alerts?: AlertUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => EmergencyContactUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => EmergencyContactUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => EmergencyContactUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  emergencyContacts?: EmergencyContactUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => EmotionRecognitionUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => EmotionRecognitionUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => EmotionRecognitionUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  emotionRecognitions?: EmotionRecognitionUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => LocationUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => LocationUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => LocationUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  locations?: LocationUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: () => VoiceCommandUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => VoiceCommandUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => VoiceCommandUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  voiceCommands?: VoiceCommandUpdateManyWithoutUsersInput;
}

export { UserUpdateInput as UserUpdateInput };
